install.packages("devtools", type = "win.binary")
devtools::install_github("gluc/ahp", build_vignettes = TRUE)
library(ahp)
ahpFile <- system.file("extdata", "telefon.ahp", package="ahp")
Tahp <- Load(ahpFile)
Calculate(Tahp)
Visualize(Tahp)
Analyze(Tahp)
Visualize(Tahp)
Analyze(Tahp)
AnalyzeTable(Tahp)